[tool.poetry]
name = "poetry-multiverse-plugin"
version = "0.1.0"
description = "Workspace support for Poetry"
authors = ["Wesley Miller <37603175+wmiller4@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
poetry = "^1.8"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.366"
ruff = "^0.4.8"
pytest = "^8.2.2"

[tool.poetry.plugins."poetry.application.plugin"]
multiverse = "poetry_multiverse_plugin.plugin:MultiversePlugin"

[tool.multiverse]
root = true

[tool.poe]
include = "tasks.toml"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
